// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.
#pragma once

#include <frc2/command/SubsystemBase.h>
#include "ctre/Phoenix.h"
#include <frc/motorcontrol/Talon.h>

/**
 *
 *
 * @author ExampleAuthor
 */
class Drive: public frc2::SubsystemBase 
{
    public:
    Drive();

        void Periodic() override;
        void SimulationPeriodic() override;
        
        double GetLeftMotorSpeed();
        double GetRightMotorSpeed();

        void SetDriveSpeed(double leftMotorSpeed,double rightMotorSpeed);


    private:

        frc::Talon *m_motorLeft;
        frc::Talon *m_motorRight;

        double m_leftMotorSpeed;
        double m_rightMotorSpeed;
        double m_setPreviousLeftSpeed;
        double m_setPreviousRightSpeed;
};