// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

#include "subsystems/Drive.h"
#include <frc/smartdashboard/SmartDashboard.h>

Drive::Drive(){
    SetName("Drive");
    SetSubsystem("Drive");

    m_motorLeft = new frc::Talon(8);
    m_motorRight = new frc::Talon(9);

    m_leftMotorSpeed = 0;
    m_rightMotorSpeed = 0;
}

void Drive::Periodic() {
    // Put code here to be run every loop

}

void Drive::SimulationPeriodic() {
    // This method will be called once per scheduler run when in simulation

}

void Drive::SetDriveSpeed(double leftMotorSpeed, double rightMotorSpeed)
{
    double clampedLeftMotorSpeed = std::clamp(leftMotorSpeed, -1.0, 1.0);
    double clampedRightMotorSpeed = std::clamp(rightMotorSpeed, -1.0, 1.0);
    m_motorLeft->Set(-clampedLeftMotorSpeed);
    m_motorRight->Set(clampedRightMotorSpeed);
}

double Drive::GetRightMotorSpeed()
{
    return m_motorRight->Get();
}

double Drive::GetLeftMotorSpeed()
{
    return m_motorLeft->Get();
}